<?xml version="1.0" encoding="UTF-8"?>
<TestCase name="tst_Xunit">
<Environment>
    <QtVersion>@INSERT_QT_VERSION_HERE@</QtVersion>
    <QtBuild/>
    <QTestVersion>@INSERT_QT_VERSION_HERE@</QTestVersion>
</Environment>
<TestFunction name="initTestCase">
<Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc1">
<Message type="warn" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[just a QWARN() !]]></Description>
</Message>
<Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc2">
<Message type="qdebug" file="" line="0">
    <Description><![CDATA[a qDebug() call with comment-ending stuff -->]]></Description>
</Message>
<Incident type="fail" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[Compared values are not the same
   Actual   (2): 2
   Expected (3): 3]]></Description>
</Incident>
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc3">
<Message type="skip" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[skipping this function!]]></Description>
</Message>
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc4">
<Incident type="fail" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[a forced failure!]]></Description>
</Incident>
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc5">
<Incident type="xfail" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[this failure is expected]]></Description>
</Incident>
<Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc6">
<Incident type="xfail" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA[this failure is also expected]]></Description>
</Incident>
<Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="testFunc7">
<Incident type="xpass" file="qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp" line="0">
    <Description><![CDATA['true' returned TRUE unexpectedly. ()]]></Description>
</Incident>
    <Duration msecs="0"/>
</TestFunction>
<TestFunction name="cleanupTestCase">
<Incident type="pass" file="" line="0" />
    <Duration msecs="0"/>
</TestFunction>
<Duration msecs="0"/>
</TestCase>
